#!/usr/bin/env python3

from LWElib import LWE
import argparse
import os

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Encrypt or Decrypt using LWE pubkey encryption')
    parser.add_argument('-m', '--message', help='message to encrypt')
    parser.add_argument('-g', '--generate', action='store_true', help='generate public and private hey pair')
    parser.add_argument('-o', '--outdir', default='~/.LWE', help='location to save files')
    parser.add_argument('-e', '--encrypt', action='store_true', help='encrypt a message')
    parser.add_argument('-d', '--decrypt', action='store_true', help='decrypt a message')
    args = parser.parse_args()
        
    app = LWE()
    if args.generate == True:
        if args.outdir != None:
            app.generate(args.outdir)
        else:
            app.generate()
    else:
        app.load(os.path.expanduser(args.outdir))
        
        if args.encrypt == True:
            if args.outdir != '~/LWE':
                with open(f'{os.path.expanduser(args.outdir)}/ct', 'wb') as file:
                    file.write(app.encrypt(args.message))
            else:
                print(app.encrypt(args.message))
        elif args.decrypt == True:
            if args.outdir != '~/LWE':
                with open(f'{os.path.expanduser(args.outdir)}/ct', 'rb') as file:
                   print(app.decrypt(file.read()))
            else:
                print(app.decrypt(args.message))
